### ISSUE TITLE
Implement template string helpers for detecting observers

### ISSUE THREAD

**Issue by fiatjaf** [calmm-js/karet#16]
Today if you write a templated string like

```js
`my count is ${Kefir.sequentially(1000, [1, 2, 3, 4, 5])}`
```

`karet` will not know there's an observable inside the string and will print `my count is [sequentially]` instead.

If there was a helper function `k`, for example, for passing template strings to, that could identify which of the template strings' variables were observers and treat them like a children. Basically just turning a template string inside a React children as multiple different children would make this work, so instead you would have to write

```js
k`my count is ${Kefir.sequentially(1000, [1, 2, 3, 4, 5])}`
```

And that's it.

What do you think? Should I submit a PR? What do you think would be the best way to implement such a feature?

**Comment by polytypic** [comment]
Thanks for the suggestion! The [Karet Util](https://github.com/calmm-js/karet.util/) library contains utilities like this.  As it happens, the (not yet documented) [`U.string`](https://github.com/calmm-js/karet.util/#U-string) function [implements](https://github.com/calmm-js/karet.util/blob/4b356cedb76cc03fc9ef1aef3d088ec095f7aa7e/src/karet.util.js#L318-L319) support for template strings with embedded observables.  (PRs for documentation are welcome!)
