### ISSUE TITLE
Help needed in porting this to RxJS

### ISSUE THREAD

**Issue by MarcCloud** [calmm-js/karet#18]
Hi.

I decided to help build a port of this library to rxjs so it is also available for projects that rely on Rx as their FRP library.

So far I have managed to port most of the functionality but I am still 2 test cases away from succeeding.

One scenario is when a single react node has more than 1 Observable embedded.

The other is that the child context test does not render.

Any help or suggestion is greatly appreciated. I have been following this project for a while and I would like to contribute in the best way I can.

Thanks in advanced

This is the source code:
https://github.com/MarcCloud/xaret/blob/master/src/xaret.js

**Comment by polytypic** [comment]
Hi!

I wonder whether Oaret (using ES7 Observables) could work for you?  See issue #17 for the discussion and links.  If it can be made to work nicely enough, it would have the major benefit of being a single unified implementation.  I must admit that I haven't yet tried Oaret myself, but I'll try to find some time ASAP to try it and see whether it could replace the existing Baret and Karet (and Xaret) implementations.

Also, I recommend joining the [Gitter channel](https://gitter.im/calmm-js/chat) and asking question there.  The main documentation for Calmm is somewhat dated as the approach has been gradually refined.

**Comment by MarcCloud** [comment]
I managed to get the port working thanks to the reference you pointed. Also, the library works in theory with any ES7 Observable but I haven't tested extensively with any other lib that is not RX.

https://github.com/MarcCloud/xaret

I will work on improving the docs and adding more practical examples.

Thank you again.
